export const DB_CREATE_PLAYLIST = 'DB_CREATE_PLAYLIST'
export const DB_ADD_ITEM = 'DB_ADD_ITEM'

export const DB_DELETE_ITEM = 'DB_DELETE_ITEM'
export const DB_UPDATE_PLAYLIST = 'DB_UPDATE_LIST'

export const DB_CREATE_USER = 'DB_CREATE_USER'

export const DB_FETCH_PLAYLISTS = 'DB_FETCH_PLAYLISTS'
export const DB_FETCH_PLAYLIST_ITEMS = 'DB_FETCH_PLAYLIST_ITEMS'

export const DB_SET_CURRENT_PLAYLIST_ID = 'DB_SET_CURRENT_PLAYLIST_ID'

export const DB_SET_PLAYLISTS_REMOVER = 'DB_SET_PLAYLISTS_REMOVER'
export const DB_SET_PLAYLIST_REMOVER = 'DB_SET_PLAYLIST_REMOVER'
